project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    
website:
  title: "Angela Lülle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: photography.qmd
        text: Photography
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css